spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://kaodigua.mysql.polardb.rds.aliyuncs.com:3306/bishe?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root_user
    password: Pee1473690
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    call-setters-on-nulls: true
  type-aliases-package: com.model
  mapper-locations: classpath:/mybatis/*.xml
logging:
  level:
    root: info
    com: debug
server:
  servlet:
    encoding:
      charset: UTF-8
