spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bishe?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root_user
    password: Pee1473690
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    call-setters-on-nulls: true
  type-aliases-package: com.model
  mapper-locations: classpath:/mybatis/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: count=countsql
logging:
  level:
    root: info
    com: debug
server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8080
